import React from 'react';
import './Person.css';

const person = (props) => { //properties dictionary passed to a component

    // use props to render dynamic content
    return (
        <div className="Person">
            <p onClick={props.click}>I'm {props.name} and I am {props.age} years old</p>
            <p>{props.children}</p>
            <input type="text" onChange={props.changed} value={props.name} />
        </div>
    )

    // use curly braces for dynamic content generated by JS
    // ie. single line expressions
    // return <p>I'm a Person and I am {Math.floor(Math.random() * 30)} years old</p>
};

export default person;